"""create business_elem table 

Revision ID: 7b555835d3b0
Revises: 07621bf36a20
Create Date: 2026-03-16 10:08:52.743393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b555835d3b0'
down_revision: Union[str, Sequence[str], None] = '07621bf36a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_elements',
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_elements')
    # ### end Alembic commands ###
