"""add relations and UK

Revision ID: 69d9abb148ed
Revises: b364c1bca710
Create Date: 2026-03-16 12:54:34.916970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69d9abb148ed"
down_revision: Union[str, Sequence[str], None] = "b364c1bca710"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_role_rules",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("element_id", sa.Integer(), nullable=False),
        sa.Column(
            "read_permission", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "read_all_permission", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "create_permission", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "update_permission", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "update_all_permission",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "delete_permission", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "delete_all_permission",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["element_id"], ["business_elements.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "element_id", name="uq_role_element"),
    )
    op.drop_constraint(op.f("fr_users_role_id"), "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fr_users_role_id"), "users", "roles", ["role_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fr_users_role_id"), "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fr_users_role_id"),
        "users",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("access_role_rules")
    # ### end Alembic commands ###
