"""add fk to table user

Revision ID: b364c1bca710
Revises: 7b555835d3b0
Create Date: 2026-03-16 11:51:07.572025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b364c1bca710"
down_revision: Union[str, Sequence[str], None] = "7b555835d3b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fr_users_role_id", "users", "roles", ["role_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fr_users_role_id", "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###
